### ISSUE TITLE
Links fail to generate for multi-word tags

### ISSUE THREAD

**Issue by shawnyeager** [qwtel/hydejack#100]
For multi-word tags (containing a space), with the corresponding featured tag created, no links are generated in the post's post-date heading.

**Comment by qwtel** [comment]
Can't reproduce, probably related to YAML usage. What works is:

```yml
# in front matter
tags: [example, content, "multi word tag"]

# in featured tags
slug: "multi word tag"
```

I'm not sure using multiword tags at all is a good idea. why not split them up into multiple tags, concatenate them, or bind them with`-` ?
