### ISSUE TITLE
Line numbers in hydejack code blocks

### ISSUE THREAD

**Issue by MilovanTomasevic** [qwtel/hydejack#150]
Is it possible to make a support for [this](https://botleg.com/stories/line-numbers-in-jekyll-code-blocks/) ?

tnx

**Comment by qwtel** [comment]
Basically, no. In fact, Hydejack doesn't support the `{% highlight %}` tag at all (the HTML generated by it is broken, doesn't even confirm to the basic HTML spec).

I agree that line numbers would be useful, but not sure how to add them. `{% highlight %}` is not the way to go. On my personal site I use comments like `// (3)` if I want to reference a specific line in the text.

**Comment by MilovanTomasevic** [comment]
It is not a fact that only the number is listed on the larger lines of code - because then someone has to count the code lines. At the moment, I did not publish the official course I'm preparing and where there are a lot of code lines so I thought there was some solution, but I believe that in the near future this will also include your development.

**Comment by Gabryxx7** [comment]
I just noticed this issue and noticed that although the HTML generated by `{% highlight %}` is not ideal it can still work and look nice.
I added some extra CSS rules to `my-style.scss`:

```CSS

td.code>pre, td.gutter.gl>pre{
  padding: 0;
  color: inherit;
  background-color: transparent !important;
  font-size: 1em;
  background-color: var(--gray-bg);
  text-align: left;
}


td.code, td.gutter.gl{
  padding: 0.25em 1em !important;
  background-color: transparent !important;
  border: none !important;
  font-size: 1.2em;
}

td.gutter.gl .lineno{
  border-right: 1px solid var(--border-color);
  padding-left: 0.5rem;
  padding-right: 0.6rem
}

figure.highlight pre{  
  padding: 0rem 0rem 0rem 1rem;
}

figure.highlight .rouge-table{
  margin-bottom: 0;
}
```

You can see the difference between the typical markdown codeblock with the three backquotes and a `{% highlight R linenos %}  <code> {% endhighlight %}` codeblock.

<img width="925" alt="Screen Shot 2019-08-20 at 5 00 07 pm" src="https://user-images.githubusercontent.com/6282055/63324741-00deda80-c36c-11e9-9236-589386171c18.png">
