### ISSUE TITLE
setup color

### ISSUE THREAD

**Issue by MilovanTomasevic** [qwtel/hydejack#158]
How to set up a new element / plugin with the theme color and not manually adjust...

On the example, I set it manually.

```css
background-color:rgb(79,177,186);
```

How to set the color on the color of the theme and how to dark theme - color?

```css
<style class="cp-pen-styles">#scroll {
    position:fixed;
    right:30px;
    bottom:30px;
    cursor:pointer;
    width:50px;
    height:50px;
    background-color: rgba(25,55,71, 0.4);
    text-indent:-9999px;
    display:none;
    -webkit-border-radius:60px;
    -moz-border-radius:60px;
    border-radius:60px
}
#scroll span {
    position:absolute;
    top:50%;
    left:50%;
    margin-left:-8px;
    margin-top:-12px;
    height:0;
    width:0;
    border:8px solid transparent;
    border-bottom-color:#ffffff;
}
#scroll:hover {
    background-color:rgb(79,177,186);
    opacity:1;filter:"alpha(opacity=100)";
    -ms-filter:"alpha(opacity=100)";
}</style>
```

How do I set it up automatically?
