### ISSUE TITLE
removing overlay from sidebar/main

### ISSUE THREAD

**Issue by salimmj** [qwtel/hydejack#169]
I am using a different background for the side bar and I don't want the gradient overlay. I'm using PRO and I'm not sure how to remove it.

**Comment by qwtel** [comment]
you can use

```yaml
accent_image:
  background: "<valid CSS background property>"
  overlay: false
```

please keep in mind that github issues is for reporting bugs, not free-of-charge support requests. thanks you.
