### ISSUE TITLE
Broken code block

### ISSUE THREAD

**Issue by martinschleiss** [qwtel/hydejack#46]
Current layout:
![screenshot from 2017-11-02 11-50-37](https://user-images.githubusercontent.com/1266338/32322253-2b05c312-bfc4-11e7-8287-0d14fd8d9ef1.png)

In my opinion the code block's scroll bar and content should be limited to the red outline as depicted in the follow image:
![screenshot from 2017-11-02 11-50-37_edit](https://user-images.githubusercontent.com/1266338/32322336-7feb0ac2-bfc4-11e7-94fb-ee114e771833.png)

**Comment by qwtel** [comment]
```yml
# file: _config.yml
hydejack:
  no_break_layout: true
```
