### ISSUE TITLE
[Help Wanted] Custom Blog Post URLs

### ISSUE THREAD

**Issue by imswebra** [qwtel/hydejack#59]
I'm looking to have the same URL format for blog posts as the projects do. For example, having `imswebra.com/posts/postname`, just a project would be `imswebra.com/projects/projectname`. As my posts are not date sensitive, I find that having the date in the url simply clutters it. I don't want to remove the date function altogether though, as I still like having them sorted by date.

As I want this to be the standard for my site (all future posts to follow this format), is there a better way to go about this besides page redirects? If this is something easily achievable, maybe it is worth explaining in the docs.

**Comment by qwtel** [comment]
Check out Jekyll's `permalink` setting.

This could work (off the top of my head):
```yaml
defaults:
  - scope:
      type: posts
    values:
      permalink: /posts/:title/
```
